# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  stripe_publishable_key: pk_test_JdtGLXc4bw7C6MmrmvO0TEBA
  stripe_secret_key: sk_test_Wy65cS54XqrHGpcoZoedRKfH

  secret_key_base: f8f30be6d3ca93e26f0b2d14e8ac2914cd9e438059c0624209af3382a2ef831ae3431abe0ba801aa4db1dd0d8c2122fefc7d69181e43128a3c40677111e03783

test:
  secret_key_base: 094d4d97f1bacef34ab9e78b487313d5f93a65674325175718ee194c59f52b42e17ae6dc4d5fab031dfa6685c24a7f940ffef018357ae3cf4e13eeb364d6d6f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_test_JdtGLXc4bw7C6MmrmvO0TEBA
  stripe_secret_key: sk_test_Wy65cS54XqrHGpcoZoedRKfH
